### ISSUE TITLE
Namespace problems

### ISSUE THREAD

**Issue by RoyBradley** [threenine/api-template#6]
After template is rung the namespace in the project `<project-name>.Content.Activities`, etc. Following you examples online where did the ... `.Content.` ... come from It was not put in the  part of the CLI template command. This cause namespace warnings.

**Comment by garywoodfine** [comment]
@RoyBradley I think this might actually be a little bug. I must have erroneously left that in from the the original project.  Surprising that you're the first to notice this. Will shortly update the template to remedy this

**Comment by garywoodfine** [comment]
@RoyBradley Updated the template the Content has now been removed

**Comment by RoyBradley** [comment]
Thank you. I have followed you for a few years. Way back then I found you auto mapper wrapper.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by garywoodfine** [comment]
Thanks for persisting with my ramblings on the internet , hopefully they have been somewhat useful :-)

**Comment by RoyBradley** [comment]
Ramble all you want; I really like your blogging. Your articles    Are first rate. So, I’m assuming that if I listen to your rambling, I will eventually I’ll find another piece of wisdom. :-)

Roy W Bradley

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by garywoodfine** [comment]
Bug was fixed and releases and is not available in 3.1.14 of the nuget package.
Going to go ahead and close this issue.  Thanks so much for the feedback

**Comment by RoyBradley** [comment]
Thank you
