### ISSUE TITLE
Installed template - error message

### ISSUE THREAD

**Issue by RoyBradley** [threenine/api-template#7]
I uninstalled the existing api-template and installed the current version and I get the error message, below. Though I seem to work fine.
PS C:\Users\ctcrrmcirb\source\repos> dotnet new --install Threenine.ApiProject
The following template packages will be installed:
   Threenine.ApiProject

Warning: Failed to scan 
Management\repos\Clean.Architecture is not supported, or doesn't exist.
Error: Failed to load template from C:\Users\xxxxxxxxx\OneDrive\Repos\Clean.Architecture\.template.config/template.json.
Details: Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: .. Path 'classifications[1]', line 4, position 52.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Microsoft.TemplateEngine.JExtensions.ReadJObjectFromIFile(IFile file)
   at Microsoft.TemplateEngine.Orchestrator.RunnableProjects.RunnableProjectGenerator.GetTemplatesAndLangpacksFromDir(IMountPoint source, IList`1& localizations)
Success: Threenine.ApiProject::3.1.14 installed the following templates:
Template Name         Short Name  Language  Tags
--------------------  ----------  --------  --------------------------
API project template  apiproject  [C#]      webapi/cqrs/vertical
Command Endpoint      command     [C#]      webapi/cqrs/vertical
Query Endpoint        query       [C#]      webapi/cqrs/vertical slice

**Comment by garywoodfine** [comment]
That is an odd one!

Looking at the error it looks like there may be a conflict with Clean Architecture
```sh
Management\repos\Clean.Architecture is not supported, or doesn't exist.
Error: Failed to load template from C:\Users\xxxxxxxxx\OneDrive\Repos\Clean.Architecture.template.config/template.json.
Details: Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: .. Path 'classifications[1]', line 4, position 52.
```

**Comment by garywoodfine** [comment]
For the life of me I am unable to replicate the issue.

Does it still occur?

**Comment by RoyBradley** [comment]
I’ll go back and check.

Roy

**Comment by garywoodfine** [comment]
@RoyBradley  I'm going to go ahead and close this issue. I was never able to recreate it and nobody else has reported it

**Comment by RoyBradley** [comment]
Sorry, please close

Roy
